version: '3'

services:
   enrollment-api-postgres:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=enrollment-api
      
   enrollment-api:
    image: node:alpine
    build: .
    tty: true
    stdin_open: true
    container_name: enrollment-api
    working_dir: /app
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=postgresql://docker:docker@enrollment-api-postgres:5432/enrollment-api?schema=public
    volumes:
      - ./:/app
    depends_on:
      - enrollment-api-postgres